# Generated by Django 5.2.13 on 2026-04-27 11:23

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=300, verbose_name='Subtítulo / Descripción breve')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido / Instrucciones')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/', verbose_name='Imagen')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], default='facil', max_length=10, verbose_name='Dificultad')),
                ('tiempo_preparacion', models.PositiveIntegerField(default=30, verbose_name='Tiempo de preparación (min)')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha'],
            },
        ),
    ]
